# Generated by Django 2.2.5 on 2019-09-30 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OpenVAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvas_requests',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='openvas_requests',
            name='state',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Running', 'Running'), ('Finished', 'Finished'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted'), ('Saved', 'Saved')], max_length=20),
        ),
    ]
