# Generated by Django 2.2.5 on 2019-10-07 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='w3af_results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('output', models.TextField(null=True)),
                ('report', models.TextField(null=True)),
                ('finish_date', models.DateTimeField(null=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='w3af_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('target_os', models.CharField(choices=[('unknown', 'unknown'), ('unix', 'unix'), ('windows', 'windows')], max_length=11)),
                ('target_framework', models.CharField(choices=[('unknown', 'unknown'), ('php', 'php'), ('asp', 'asp'), ('asp.net', 'asp.net'), ('java', 'java'), ('jsp', 'jsp'), ('cfm', 'cfm'), ('ruby', 'ruby'), ('perl', 'perl')], max_length=11)),
                ('profile', models.CharField(choices=[('Fast Scan', 'Fast Scan'), ('Full Audit', 'Full Audit'), ('OWASP Top 10', 'OWASP Scan')], max_length=10)),
                ('login_url', models.CharField(max_length=100, null=True)),
                ('login_username', models.CharField(max_length=30, null=True)),
                ('login_password', models.CharField(max_length=30, null=True)),
                ('login_userfield', models.CharField(max_length=30, null=True)),
                ('login_passwordfield', models.CharField(max_length=30, null=True)),
                ('login_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=30, null=True)),
                ('http_domain', models.CharField(max_length=100, null=True)),
                ('http_user', models.CharField(max_length=30, null=True)),
                ('http_password', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(choices=[('On Hold', 'On Hold'), ('Running', 'Running'), ('Finished', 'Finished'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted'), ('Saved', 'Saved')], max_length=20)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='date modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
