from __future__ import unicode_literals
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


# Here the task results will be stored with their previous ID
class w3af_results(models.Model):
    id = models.IntegerField(primary_key=True)
    output = models.TextField(null=True)
    report = models.TextField(null=True)
    finish_date = models.DateTimeField('date created', null=True)


# Create your models here.
class w3af_requests(models.Model):
    # ID autogenerated as primary key

    Profiles = (('Fast Scan', 'Fast Scan'), ('Full Audit', 'Full Audit'), ('OWASP Top 10', 'OWASP Scan'))
    Target_OSs = (('unknown', 'unknown'), ('unix', 'unix'), ('windows', 'windows'))
    Target_frameworks = (
    ('unknown', 'unknown'), ('php', 'php'), ('asp', 'asp'), ('asp.net', 'asp.net'), ('java', 'java'),
    ('jsp', 'jsp'), ('cfm', 'cfm'), ('ruby', 'ruby'), ('perl', 'perl'))

    Methods = (('POST', 'POST'), ('GET', 'GET'))

    States = (('On Hold', 'On Hold'), ('Running', 'Running'), ('Finished', 'Finished'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted'), ('Saved', 'Saved'))

    # Task name
    name = models.CharField(max_length=100)

    # User
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Target
    target = models.CharField(max_length=100)
    target_os = models.CharField(choices=Target_OSs, max_length=11)
    target_framework = models.CharField(choices=Target_frameworks, max_length=11)

    # Config (plugins)
    profile = models.CharField(choices=Profiles, max_length=10)

    # Autenticathion
    login_url = models.CharField(max_length=100, null=True)
    login_username = models.CharField(max_length=30, null=True)
    login_password = models.CharField(max_length=30, null=True)
    login_userfield = models.CharField(max_length=30, null=True)
    login_passwordfield = models.CharField(max_length=30, null=True)
    login_method = models.CharField(choices=Methods, max_length=30, null=True)

    # HTTP Basic Auth
    http_domain = models.CharField(max_length=100, null=True)
    http_user = models.CharField(max_length=30, null=True)
    http_password = models.CharField(max_length=30, null=True)

    # Altres
    state = models.CharField(choices=States, max_length=20)
    mail = models.CharField(max_length=100, null=True)

    # Guardem la data d'insercio
    insert_date = models.DateTimeField('date created', default=datetime.now)

    # Guardem la data de modificacio
    modify_date = models.DateTimeField('date modified', null=True)
