from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

# Here the task results will be stored with their previous ID
class openvas_results(models.Model):
    id = models.IntegerField(primary_key=True)
    report = models.CharField(null=True, max_length=50)
    output = models.TextField(null=True)
    finish_date = models.DateTimeField('date created', null=True)

class openvas_requests(models.Model):
    # ID autogenerated as primary key

    States = (('On Hold', 'On Hold'), ('Running', 'Running'), ('Finished', 'Finished'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted'), ('Saved', 'Saved'))
    ScanConfigs = (
    ('Discovery', 'Discovery'), ('Full and fast', 'Full and fast'), ('Full and fast ultimate', 'Full and fast ultimate'), ('Full and very deep', 'Full and very deep'), ('Full and very deep ultimate', 'Full and very deep ultimate'))

    # Task name
    name = models.CharField(max_length=100)

    # User
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # State
    state = models.CharField(choices=States, max_length=20)

    #Scan config
    config = models.CharField(choices=ScanConfigs, max_length=30)

    # Percentage
    percentage = models.IntegerField()

    # Target
    target = models.CharField(max_length=100)

    # Mail
    mail = models.CharField(max_length=100, null=True)

    #Saving inserting date
    insert_date = models.DateTimeField('date created', default=datetime.now)

    # Saving modify date
    modify_date = models.DateTimeField('date modified', null=True)


